-- database: one_to_many_example

DROP TABLE IF EXISTS BOOK_GENRE;

DROP TABLE IF EXISTS BOOK;

DROP TABLE IF EXISTS CHAPTER_HIERERCHY;

DROP TABLE IF EXISTS CHAPTER;

DROP TABLE IF EXISTS SECTION;

DROP TABLE IF EXISTS GENRE;

DROP TABLE IF EXISTS AUTHOR;


CREATE TABLE SECTION (
	id BIGINT(20) NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
	section_text TEXT NOT NULL,
	style TEXT,
	section_length INTEGER NOT NULL
);


CREATE TABLE GENRE (
	id BIGINT(20) NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
	short_name VARCHAR(10) NOT NULL,
	name VARCHAR(100) NOT NULL
);


CREATE TABLE AUTHOR (
	id BIGINT(20) NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
	first_name VARCHAR(200) NOT NULL,
	last_name VARCHAR(200) NOT NULL
);


CREATE TABLE CHAPTER (
	id BIGINT(20) NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
	title TEXT NOT NULL,
	plot_sumary TEXT,
	content_id BIGINT(20) NOT NULL,
	FOREIGN KEY (content_id) REFERENCES SECTION(id)
);


CREATE TABLE CHAPTER_HIERERCHY (
	parent_id BIGINT(20) NOT NULL,
	child_id BIGINT(20) NOT NULL,
	FOREIGN KEY (parent_id) REFERENCES CHAPTER(id),
	FOREIGN KEY (child_id) REFERENCES CHAPTER(id)
);


CREATE TABLE BOOK (
	id BIGINT(20) NOT NULL UNIQUE PRIMARY KEY AUTO_INCREMENT,
	title TEXT NOT NULL,
	author_id BIGINT(20) NOT NULL,
	main_chapter_id BIGINT(20) NOT NULL,
	FOREIGN KEY (author_id) REFERENCES AUTHOR(id),
	FOREIGN KEY (main_chapter_id) REFERENCES CHAPTER(id)
);


CREATE TABLE BOOK_GENRE (
	book_id BIGINT(20) NOT NULL,
	genre_id BIGINT(20) NOT NULL,
	FOREIGN KEY (book_id) REFERENCES BOOK(id),
	FOREIGN KEY (genre_id) REFERENCES GENRE(id)
);

