DROP SEQUENCE IF EXISTS SEQ_AUTHOR_ID;
DROP SEQUENCE IF EXISTS SEQ_BOOK_ID;
DROP SEQUENCE IF EXISTS SEQ_CHAPTER_ID;
DROP SEQUENCE IF EXISTS SEQ_GENRE_ID;
DROP SEQUENCE IF EXISTS SEQ_SECTION_ID;

CREATE SEQUENCE SEQ_AUTHOR_ID;
CREATE SEQUENCE SEQ_BOOK_ID;
CREATE SEQUENCE SEQ_CHAPTER_ID;
CREATE SEQUENCE SEQ_GENRE_ID;
CREATE SEQUENCE SEQ_SECTION_ID;


DROP TABLE IF EXISTS BOOK_GENRE;

DROP TABLE IF EXISTS BOOK;

DROP TABLE IF EXISTS CHAPTER_HIERERCHY;

DROP TABLE IF EXISTS CHAPTER;

DROP TABLE IF EXISTS SECTION;

DROP TABLE IF EXISTS GENRE;

DROP TABLE IF EXISTS AUTHOR;


CREATE TABLE SECTION (
	id NUMERIC(20, 0) NOT NULL PRIMARY KEY,
	section_text CLOB NOT NULL,
	style CLOB,
	section_length INTEGER NOT NULL
);


CREATE TABLE GENRE (
	id NUMERIC(20, 0) NOT NULL PRIMARY KEY,
	short_name VARCHAR(10) NOT NULL,
	name VARCHAR(100) NOT NULL
);


CREATE TABLE AUTHOR (
	id NUMERIC(20, 0) NOT NULL PRIMARY KEY,
	first_name VARCHAR(200) NOT NULL,
	last_name VARCHAR(200) NOT NULL
);


CREATE TABLE CHAPTER (
	id NUMERIC(20, 0) NOT NULL PRIMARY KEY,
	title CLOB NOT NULL,
	plot_summary CLOB,
	content_id NUMERIC(20, 0) NOT NULL,
	FOREIGN KEY (content_id) REFERENCES SECTION(id)
);


CREATE TABLE CHAPTER_HIERERCHY (
	parent_id NUMERIC(20, 0) NOT NULL,
	child_id NUMERIC(20, 0) NOT NULL,
	FOREIGN KEY (parent_id) REFERENCES CHAPTER(id),
	FOREIGN KEY (child_id) REFERENCES CHAPTER(id)
);


CREATE TABLE BOOK (
	id NUMERIC(20, 0) NOT NULL PRIMARY KEY,
	title CLOB NOT NULL,
	author_id NUMERIC(20, 0) NOT NULL,
	main_chapter_id NUMERIC(20, 0) NOT NULL,
	FOREIGN KEY (author_id) REFERENCES AUTHOR(id),
	FOREIGN KEY (main_chapter_id) REFERENCES CHAPTER(id)
);


CREATE TABLE BOOK_GENRE (
	book_id NUMERIC(20, 0) NOT NULL,
	genre_id NUMERIC(20, 0) NOT NULL,
	FOREIGN KEY (book_id) REFERENCES BOOK(id),
	FOREIGN KEY (genre_id) REFERENCES GENRE(id)
);

