enum MenuAction {
    SHOW_ALL_GENRES = 'SHOW_ALL_GENRES',
    ADD_NEW_GENRE = 'ADD_NEW_GENRE',
    SHOW_ALL_AUTHORS = 'SHOW_ALL_AUTHORS',
    ADD_NEW_AUTHOR = 'ADD_NEW_AUTHOR',
    SHOW_ALL_BOOKS = 'SHOW_ALL_BOOKS',
    ADD_NEW_BOOK = 'ADD_NEW_BOOK'
}

export default MenuAction;
